### ISSUE TITLE
domain librefox.com

### ISSUE THREAD

**Issue by intika** [bjm1904/LibreFox#1]
hello 

are you interested in selling your domain ?

thanks

**Comment by bjm1904** [comment]
If you're a company trying to sell it for me, then no!
Otherwise, drop me an email via bob@bobstechsite.com and make me an offer :)

**Comment by bjm1904** [comment]
FYI domains available:
librefox.com: Expires Feb 2017
librefox.co.uk: Expires Feb 2024
librefox.net: Expires Feb 2016

These aren't intensionally squatted. Just unfortunately never got around to developing the project.

**Comment by intika** [comment]
thanks for the answer :) i picked an other name for the project thanks anyway ;)
i am making some new open extensions for firefox they should interest you any way i'll write here once i have a finish product ;)
